// Catálogo CIE-10 (Clasificación Internacional de Enfermedades, 10a revisión)
// Códigos de 3 caracteres más frecuentes en consulta general y salud
// ocupacional (OMS/OPS), en español. No es el catálogo completo (~14,000
// códigos); es un subconjunto curado de los ~200 más usados en este contexto.
// Los formularios que lo usan siempre ofrecen una opción "Otros" con texto
// libre para los casos no cubiertos aquí.

export const CIE10 = [
  // Capítulo I - Enfermedades infecciosas y parasitarias (A00-B99)
  { codigo: 'A00', descripcion: 'Cólera' },
  { codigo: 'A01', descripcion: 'Fiebre tifoidea y paratifoidea' },
  { codigo: 'A02', descripcion: 'Otras infecciones debidas a Salmonella' },
  { codigo: 'A04', descripcion: 'Otras infecciones intestinales bacterianas' },
  { codigo: 'A08', descripcion: 'Infecciones intestinales debidas a virus' },
  { codigo: 'A09', descripcion: 'Diarrea y gastroenteritis de presunto origen infeccioso' },
  { codigo: 'A15', descripcion: 'Tuberculosis respiratoria' },
  { codigo: 'A49', descripcion: 'Infección bacteriana de sitio no especificado' },
  { codigo: 'A63', descripcion: 'Verrugas anogenitales (por virus del papiloma humano)' },
  { codigo: 'B01', descripcion: 'Varicela' },
  { codigo: 'B05', descripcion: 'Sarampión' },
  { codigo: 'B06', descripcion: 'Rubéola' },
  { codigo: 'B18', descripcion: 'Hepatitis viral crónica' },
  { codigo: 'B34', descripcion: 'Infección viral de sitio no especificado' },
  { codigo: 'B35', descripcion: 'Dermatofitosis (tiña)' },
  { codigo: 'B37', descripcion: 'Candidiasis' },
  { codigo: 'B82', descripcion: 'Parasitosis intestinal, sin otra especificación' },

  // Capítulo II - Neoplasias (C00-D48)
  { codigo: 'C50', descripcion: 'Tumor maligno de la mama' },
  { codigo: 'C61', descripcion: 'Tumor maligno de la próstata' },
  { codigo: 'C73', descripcion: 'Tumor maligno de la glándula tiroides' },
  { codigo: 'D17', descripcion: 'Tumor benigno de tejido adiposo (lipoma)' },
  { codigo: 'D22', descripcion: 'Nevo melanocítico' },
  { codigo: 'D50', descripcion: 'Anemia por deficiencia de hierro' },
  { codigo: 'D64', descripcion: 'Otras anemias' },

  // Capítulo IV - Enfermedades endocrinas, nutricionales y metabólicas (E00-E90)
  { codigo: 'E03', descripcion: 'Otros hipotiroidismos' },
  { codigo: 'E04', descripcion: 'Otros bocios no tóxicos' },
  { codigo: 'E05', descripcion: 'Tirotoxicosis (hipertiroidismo)' },
  { codigo: 'E10', descripcion: 'Diabetes mellitus tipo 1' },
  { codigo: 'E11', descripcion: 'Diabetes mellitus tipo 2' },
  { codigo: 'E14', descripcion: 'Diabetes mellitus, no especificada' },
  { codigo: 'E16', descripcion: 'Otros trastornos de la secreción interna del páncreas (hipoglucemia)' },
  { codigo: 'E55', descripcion: 'Deficiencia de vitamina D' },
  { codigo: 'E66', descripcion: 'Obesidad' },
  { codigo: 'E78', descripcion: 'Trastornos del metabolismo de lipoproteínas (dislipidemia)' },
  { codigo: 'E86', descripcion: 'Deplección del volumen (deshidratación)' },

  // Capítulo V - Trastornos mentales y del comportamiento (F00-F99)
  { codigo: 'F32', descripcion: 'Episodio depresivo' },
  { codigo: 'F33', descripcion: 'Trastorno depresivo recurrente' },
  { codigo: 'F41', descripcion: 'Otros trastornos de ansiedad' },
  { codigo: 'F43', descripcion: 'Reacción a estrés grave y trastornos de adaptación (incluye estrés laboral/burnout)' },
  { codigo: 'F45', descripcion: 'Trastornos somatomorfos' },
  { codigo: 'F51', descripcion: 'Trastornos no orgánicos del sueño (insomnio)' },

  // Capítulo VI - Enfermedades del sistema nervioso (G00-G99)
  { codigo: 'G43', descripcion: 'Migraña' },
  { codigo: 'G44', descripcion: 'Otros síndromes de cefalea' },
  { codigo: 'G47', descripcion: 'Trastornos del sueño' },
  { codigo: 'G56', descripcion: 'Mononeuropatías del miembro superior (síndrome del túnel carpiano)' },
  { codigo: 'G62', descripcion: 'Otras polineuropatías' },

  // Capítulo VII - Enfermedades del ojo y anexos (H00-H59)
  { codigo: 'H00', descripcion: 'Orzuelo y calacio' },
  { codigo: 'H10', descripcion: 'Conjuntivitis' },
  { codigo: 'H52', descripcion: 'Trastornos de la acomodación y de la refracción' },
  { codigo: 'H53', descripcion: 'Alteraciones visuales' },

  // Capítulo VIII - Enfermedades del oído y apófisis mastoides (H60-H95)
  { codigo: 'H61', descripcion: 'Otros trastornos del oído externo (tapón de cerumen)' },
  { codigo: 'H65', descripcion: 'Otitis media no supurativa' },
  { codigo: 'H66', descripcion: 'Otitis media supurativa y la no especificada' },
  { codigo: 'H81', descripcion: 'Trastornos de la función vestibular (vértigo)' },
  { codigo: 'H90', descripcion: 'Hipoacusia conductiva y neurosensorial' },
  { codigo: 'H91', descripcion: 'Otras hipoacusias (incluye hipoacusia inducida por ruido)' },

  // Capítulo IX - Enfermedades del sistema circulatorio (I00-I99)
  { codigo: 'I10', descripcion: 'Hipertensión esencial (primaria)' },
  { codigo: 'I20', descripcion: 'Angina de pecho' },
  { codigo: 'I21', descripcion: 'Infarto agudo del miocardio' },
  { codigo: 'I25', descripcion: 'Enfermedad isquémica crónica del corazón' },
  { codigo: 'I48', descripcion: 'Fibrilación y aleteo auricular' },
  { codigo: 'I83', descripcion: 'Várices de los miembros inferiores' },
  { codigo: 'I95', descripcion: 'Hipotensión' },

  // Capítulo X - Enfermedades del sistema respiratorio (J00-J99)
  { codigo: 'J00', descripcion: 'Rinofaringitis aguda (resfriado común)' },
  { codigo: 'J01', descripcion: 'Sinusitis aguda' },
  { codigo: 'J02', descripcion: 'Faringitis aguda' },
  { codigo: 'J03', descripcion: 'Amigdalitis aguda' },
  { codigo: 'J06', descripcion: 'Infección aguda de vías respiratorias superiores' },
  { codigo: 'J11', descripcion: 'Influenza (gripe)' },
  { codigo: 'J18', descripcion: 'Neumonía, organismo no especificado' },
  { codigo: 'J20', descripcion: 'Bronquitis aguda' },
  { codigo: 'J30', descripcion: 'Rinitis alérgica y vasomotora' },
  { codigo: 'J31', descripcion: 'Rinitis, nasofaringitis y faringitis crónicas' },
  { codigo: 'J32', descripcion: 'Sinusitis crónica' },
  { codigo: 'J35', descripcion: 'Enfermedades crónicas de las amígdalas y adenoides' },
  { codigo: 'J44', descripcion: 'Enfermedad pulmonar obstructiva crónica (EPOC)' },
  { codigo: 'J45', descripcion: 'Asma' },
  { codigo: 'J62', descripcion: 'Neumoconiosis debida a polvo de sílice' },
  { codigo: 'J63', descripcion: 'Neumoconiosis debida a otros polvos inorgánicos' },
  { codigo: 'J66', descripcion: 'Enfermedad de las vías respiratorias debida a polvo orgánico específico' },
  { codigo: 'J98', descripcion: 'Otros trastornos respiratorios' },

  // Capítulo XI - Enfermedades del sistema digestivo (K00-K93)
  { codigo: 'K02', descripcion: 'Caries dental' },
  { codigo: 'K04', descripcion: 'Enfermedades de la pulpa y de los tejidos periapicales' },
  { codigo: 'K05', descripcion: 'Gingivitis y enfermedades periodontales' },
  { codigo: 'K21', descripcion: 'Enfermedad de reflujo gastroesofágico' },
  { codigo: 'K25', descripcion: 'Úlcera gástrica' },
  { codigo: 'K27', descripcion: 'Úlcera péptica, sitio no especificado' },
  { codigo: 'K29', descripcion: 'Gastritis y duodenitis' },
  { codigo: 'K30', descripcion: 'Dispepsia' },
  { codigo: 'K35', descripcion: 'Apendicitis aguda' },
  { codigo: 'K40', descripcion: 'Hernia inguinal' },
  { codigo: 'K52', descripcion: 'Otras colitis y gastroenteritis no infecciosas' },
  { codigo: 'K58', descripcion: 'Síndrome del intestino irritable' },
  { codigo: 'K59', descripcion: 'Otros trastornos funcionales del intestino (estreñimiento)' },
  { codigo: 'K76', descripcion: 'Otras enfermedades del hígado' },
  { codigo: 'K80', descripcion: 'Colelitiasis' },
  { codigo: 'K81', descripcion: 'Colecistitis' },
  { codigo: 'K85', descripcion: 'Pancreatitis aguda' },

  // Capítulo XII - Enfermedades de la piel y del tejido subcutáneo (L00-L99)
  { codigo: 'L01', descripcion: 'Impétigo' },
  { codigo: 'L02', descripcion: 'Absceso cutáneo, furúnculo y ántrax' },
  { codigo: 'L03', descripcion: 'Celulitis' },
  { codigo: 'L20', descripcion: 'Dermatitis atópica' },
  { codigo: 'L23', descripcion: 'Dermatitis alérgica de contacto' },
  { codigo: 'L24', descripcion: 'Dermatitis de contacto por irritantes' },
  { codigo: 'L25', descripcion: 'Dermatitis de contacto, no especificada (incluye ocupacional)' },
  { codigo: 'L30', descripcion: 'Otras dermatitis' },
  { codigo: 'L50', descripcion: 'Urticaria' },
  { codigo: 'L60', descripcion: 'Trastornos de las uñas' },
  { codigo: 'L72', descripcion: 'Quistes foliculares de la piel y del tejido subcutáneo' },

  // Capítulo XIII - Enfermedades del sistema osteomuscular y del tejido conjuntivo (M00-M99)
  { codigo: 'M10', descripcion: 'Gota' },
  { codigo: 'M15', descripcion: 'Poliartrosis' },
  { codigo: 'M17', descripcion: 'Gonartrosis (artrosis de la rodilla)' },
  { codigo: 'M19', descripcion: 'Otras artrosis' },
  { codigo: 'M25', descripcion: 'Otros trastornos articulares' },
  { codigo: 'M40', descripcion: 'Cifosis y lordosis' },
  { codigo: 'M41', descripcion: 'Escoliosis' },
  { codigo: 'M42', descripcion: 'Osteocondrosis de la columna vertebral' },
  { codigo: 'M43', descripcion: 'Otras dorsopatías deformantes' },
  { codigo: 'M45', descripcion: 'Espondilitis anquilosante' },
  { codigo: 'M47', descripcion: 'Espondilosis' },
  { codigo: 'M48', descripcion: 'Otras espondilopatías' },
  { codigo: 'M50', descripcion: 'Trastornos de los discos cervicales' },
  { codigo: 'M51', descripcion: 'Otros trastornos de los discos intervertebrales' },
  { codigo: 'M53', descripcion: 'Otras dorsopatías, no clasificadas en otra parte' },
  { codigo: 'M54', descripcion: 'Dorsalgia (incluye lumbalgia y cervicalgia)' },
  { codigo: 'M60', descripcion: 'Miositis' },
  { codigo: 'M62', descripcion: 'Otros trastornos musculares' },
  { codigo: 'M65', descripcion: 'Sinovitis y tenosinovitis' },
  { codigo: 'M70', descripcion: 'Trastornos de tejidos blandos relacionados con uso, sobreuso y presión de origen ocupacional' },
  { codigo: 'M71', descripcion: 'Otras bursopatías' },
  { codigo: 'M75', descripcion: 'Lesiones del hombro' },
  { codigo: 'M77', descripcion: 'Otras entesopatías (epicondilitis)' },
  { codigo: 'M79', descripcion: 'Otros trastornos de los tejidos blandos, no clasificados (mialgia)' },
  { codigo: 'M54.5', descripcion: 'Lumbago no especificado' },

  // Capítulo XIV - Enfermedades del sistema genitourinario (N00-N99)
  { codigo: 'N20', descripcion: 'Cálculo renal y ureteral' },
  { codigo: 'N30', descripcion: 'Cistitis' },
  { codigo: 'N39', descripcion: 'Infección de vías urinarias, sitio no especificado' },
  { codigo: 'N40', descripcion: 'Hiperplasia de la próstata' },
  { codigo: 'N76', descripcion: 'Otras afecciones inflamatorias de la vagina y de la vulva' },
  { codigo: 'N92', descripcion: 'Menstruación excesiva, frecuente e irregular' },
  { codigo: 'N94', descripcion: 'Dolor y otras afecciones relacionadas con órganos genitales femeninos' },

  // Capítulo XV - Embarazo, parto y puerperio (O00-O99)
  { codigo: 'O10', descripcion: 'Hipertensión preexistente que complica el embarazo' },
  { codigo: 'O14', descripcion: 'Preeclampsia' },
  { codigo: 'O21', descripcion: 'Vómitos excesivos en el embarazo' },
  { codigo: 'O23', descripcion: 'Infección de las vías genitourinarias en el embarazo' },
  { codigo: 'O26', descripcion: 'Atención a la madre por otras complicaciones del embarazo' },
  { codigo: 'O47', descripcion: 'Falso trabajo de parto' },
  { codigo: 'O60', descripcion: 'Parto prematuro' },
  { codigo: 'O80', descripcion: 'Parto único espontáneo' },
  { codigo: 'O99', descripcion: 'Otras enfermedades maternas clasificables en otra parte que complican el embarazo' },
  { codigo: 'Z34', descripcion: 'Supervisión de embarazo normal' },

  // Capítulo XVIII - Síntomas, signos y hallazgos anormales (R00-R99)
  { codigo: 'R05', descripcion: 'Tos' },
  { codigo: 'R06', descripcion: 'Anormalidades de la respiración (disnea)' },
  { codigo: 'R07', descripcion: 'Dolor de garganta y en el pecho' },
  { codigo: 'R10', descripcion: 'Dolor abdominal y pélvico' },
  { codigo: 'R11', descripcion: 'Náusea y vómito' },
  { codigo: 'R42', descripcion: 'Mareo y desvanecimiento' },
  { codigo: 'R50', descripcion: 'Fiebre de origen desconocido' },
  { codigo: 'R51', descripcion: 'Cefalea' },
  { codigo: 'R53', descripcion: 'Malestar y fatiga' },
  { codigo: 'R55', descripcion: 'Síncope y colapso' },
  { codigo: 'R73', descripcion: 'Hiperglicemia, no especificada' },

  // Capítulo XIX - Traumatismos, envenenamientos y consecuencias de causas externas (S00-T98)
  { codigo: 'S00', descripcion: 'Traumatismo superficial de la cabeza' },
  { codigo: 'S01', descripcion: 'Herida de la cabeza' },
  { codigo: 'S06', descripcion: 'Traumatismo intracraneal' },
  { codigo: 'S09', descripcion: 'Otros traumatismos de la cabeza, no especificados' },
  { codigo: 'S20', descripcion: 'Traumatismo superficial del tórax' },
  { codigo: 'S42', descripcion: 'Fractura del hombro y del brazo' },
  { codigo: 'S43', descripcion: 'Luxación, esguince y torcedura del hombro' },
  { codigo: 'S52', descripcion: 'Fractura del antebrazo' },
  { codigo: 'S60', descripcion: 'Traumatismo superficial de la muñeca y de la mano' },
  { codigo: 'S61', descripcion: 'Herida de la muñeca y de la mano' },
  { codigo: 'S62', descripcion: 'Fractura a nivel de la muñeca y de la mano' },
  { codigo: 'S69', descripcion: 'Otros traumatismos de la muñeca y de la mano, no especificados' },
  { codigo: 'S72', descripcion: 'Fractura del fémur' },
  { codigo: 'S82', descripcion: 'Fractura de la pierna, incluido el tobillo' },
  { codigo: 'S83', descripcion: 'Luxación, esguince y torcedura de la rodilla' },
  { codigo: 'S90', descripcion: 'Traumatismo superficial del tobillo y del pie' },
  { codigo: 'S91', descripcion: 'Herida del tobillo y del pie' },
  { codigo: 'S93', descripcion: 'Luxación, esguince y torcedura de las articulaciones del tobillo y del pie' },
  { codigo: 'T14', descripcion: 'Traumatismo de región no especificada del cuerpo' },
  { codigo: 'T15', descripcion: 'Cuerpo extraño en el ojo' },
  { codigo: 'T20', descripcion: 'Quemadura de la cabeza y del cuello' },
  { codigo: 'T22', descripcion: 'Quemadura del hombro y del miembro superior, excepto muñeca y mano' },
  { codigo: 'T23', descripcion: 'Quemadura de la muñeca y de la mano' },
  { codigo: 'T30', descripcion: 'Quemadura, región del cuerpo no especificada' },
  { codigo: 'T65', descripcion: 'Efecto tóxico de otras sustancias no especificadas' },
  { codigo: 'T78', descripcion: 'Reacción anafiláctica, no especificada' },

  // Capítulo XX - Causas externas de morbilidad y mortalidad (V01-Y98)
  { codigo: 'W00', descripcion: 'Caída por resbalón, tropiezo con hielo o nieve' },
  { codigo: 'W01', descripcion: 'Caída al mismo nivel por resbalón, tropiezo o traspié' },
  { codigo: 'W10', descripcion: 'Caída en o desde escaleras y escalones' },
  { codigo: 'W17', descripcion: 'Otra caída de un nivel a otro' },
  { codigo: 'W18', descripcion: 'Otras caídas al mismo nivel' },
  { codigo: 'W20', descripcion: 'Golpe por objeto lanzado, proyectado o que cae' },
  { codigo: 'W24', descripcion: 'Traumatismo por objetos de elevación y transmisión, no especificados' },
  { codigo: 'W31', descripcion: 'Contacto con otra maquinaria en marcha y la no especificada' },
  { codigo: 'W40', descripcion: 'Explosión de otros materiales' },
  { codigo: 'W45', descripcion: 'Cuerpo extraño o un objeto que penetra a través de la piel' },
  { codigo: 'W54', descripcion: 'Mordedura o ataque de perro' },
  { codigo: 'W57', descripcion: 'Mordedura o picadura de insecto no venenoso u otro artrópodo no venenoso' },
  { codigo: 'X30', descripcion: 'Exposición a calor natural excesivo' },
  { codigo: 'X31', descripcion: 'Exposición a frío natural excesivo' },
  { codigo: 'Y96', descripcion: 'Circunstancia relativa a las condiciones de trabajo' },

  // Capítulo XXI - Factores que influyen en el estado de salud (Z00-Z99)
  { codigo: 'Z00', descripcion: 'Examen general e investigación de personas sin quejas o diagnóstico reportado' },
  { codigo: 'Z01', descripcion: 'Otros exámenes especiales e investigaciones en personas sin quejas' },
  { codigo: 'Z02', descripcion: 'Examen para fines administrativos (incluye examen médico de aptitud para el empleo)' },
  { codigo: 'Z10', descripcion: 'Examen médico general de rutina de subpoblación definida (medicina ocupacional)' },
  { codigo: 'Z29', descripcion: 'Necesidad de otras medidas profilácticas' },
  { codigo: 'Z30', descripcion: 'Atención para la anticoncepción' },
  { codigo: 'Z32', descripcion: 'Examen y prueba de embarazo' },
  { codigo: 'Z33', descripcion: 'Estado de embarazo, incidental' },
  { codigo: 'Z56', descripcion: 'Problemas relacionados con el empleo y el desempleo' },
  { codigo: 'Z57', descripcion: 'Exposición ocupacional a factores de riesgo' },
  { codigo: 'Z71', descripcion: 'Personas en contacto con los servicios de salud para otras consultas y consejo médico' },
  { codigo: 'Z72', descripcion: 'Problemas relacionados con el estilo de vida' },
  { codigo: 'Z73', descripcion: 'Problemas relacionados con dificultades para afrontar la vida (estrés)' },
  { codigo: 'Z76', descripcion: 'Personas en contacto con los servicios de salud en otras circunstancias' },
];

export const OTROS_CIE10 = 'OTROS';
